#!/bin/bash

declare -a includes
declare -a targets

targetCount=0
count=0

CMDSFILE=cmds.txt
SESSION=${HOSTNAME}.`date +%F.%H-%M-%s`.${RANDOM}
SCRIPT=${SESSION}.sh
TARFILE=${SESSION}.tgz

#
# 0. Create Execute script
# 1. Tar up files
# 2. Copy TAR file and Execute Script over to target
# 3. Execute Script
#
# Tar file must contain all required files and a "cmds.txt" file to be fed to the execute script
#

# Usage
function Usage()
{
	echo -e "RDS - Remote Distributed Scripting"
	echo -e "=================================="
	echo -e "rds -t [target host] -c [cmd file] [file 1] [file 2] ... [file n]"
	echo -e "rds -f [list of targets] -c [cmd file] [file 1] [file 2] ... [file n]"
	echo -e "rds -p [profile]"
	echo -e "=================================="
	echo -e "RDS defaults to 'cmds.txt' if command file not provided"
	echo -e "* Generally only works when in an SSH-AGENT Shell"
}

# Create Execution Script
function CreateExecuteScript()
{
	cat > /tmp/${SESSION}/${SCRIPT}<<eof
#!/bin/bash
pushd /tmp > /dev/null

tar -xzf ${TARFILE}

rm ${TARFILE}

pushd /tmp/${SESSION} > /dev/null

while read line; do
	eval "\${line}"
done < ${CMDSFILE}

dirs -c > /dev/null

rm -R /tmp/${SESSION}
eof

	chmod u+rx /tmp/${SCRIPT}
}

# Add host To Target
# Parameters : [host]
function AddTarget()
{
	targets[${targetCount}]="${1}"
	targetCount=$(( ${targetCount} + 1 ))
}

# Add Targets To Target
# Parameters : [target file]
function AddTargets()
{
	while read target rem; do
		AddTarget "${target}"
	done < "${1}"
}

# AddFile : To includes
# Parameter : [filename]
function AddFile()
{
	includes[${count}]="${1}"
	count=$(( ${count} + 1 ))
}

# ProcessProfile : Process profile
# Parameters : [profile]
function ProcessProfile()
{
	while read label value1 value2 value3 value4; do
		case "${label}" in
		"target")	AddTarget "${value1}" ;;
		"file")		AddFile "${value1}" ;;
		"cmds")		CMDSFILE="${value1}" ;;
		esac
	done < "${1}"
}

# CreateSession : Create Session folder
function CreateSession()
{
	echo -e "Creating Session..."
	mkdir /tmp/${SESSION}

	CreateExecuteScript

	cp "${CMDSFILE}" /tmp/${SESSION}

	for ((index=0; index < ${#includes[@]}; ++index)); do
		cp ${includes[${index}]} /tmp/${SESSION}
	done
}

#
# Main Loop
#

while [ ! "${1}" = "" ]; do
	case "${1}" in
	"-t")	AddTarget "${2}"
		shift 1 ;;
	"-f")	AddTargets "${2}"
		shift 1 ;;
	"-p")	ProcessProfile "${2}"
		shift 1 ;;
	"-h")	Usage
		exit ;;
	"-c")	CMDSFILE="${2}"
		shift 1 ;;
	*)	AddFile "${1}" ;;
	esac

	shift 1
done

if [ -f ${CMDSFILE} ]; then

	[ ! -f /tmp/${SESSION} ] && CreateSession

	pushd /tmp > /dev/null

	echo -e "Packing files for transfer..."
	tar -czf ${TARFILE} ${SESSION}

	for ((index=0; index < ${#targets[@]}; ++index)); do
		TARGET=${targets[${index}]}
		echo -e "--> Transferring to ${TARGET}..."
		echo -e "Transferring control script..."
		scp /tmp/${SESSION}/${SCRIPT} ${USERNAME}@${TARGET}:/tmp/${SCRIPT} > /dev/null
		echo -e "Transferring files..."
		scp /tmp/${TARFILE} ${USERNAME}@${TARGET}:/tmp/${TARFILE} > /dev/null
		echo -e "Executing control script..."
		slogin ${USERNAME}${TARGET} "/bin/bash /tmp/${SCRIPT}" > /dev/null
		echo -e "Cleaning up.."
		slogin ${USERNAME}${TARGET} "rm /tmp/${SCRIPT}" > /dev/null
		echo -e "Done..."
	done

	popd > /dev/null
fi

[ -e /tmp/${SCRIPT} ] && rm /tmp/${SCRIPT}
[ -e /tmp/${TARFILE} ] && rm /tmp/${TARFILE}
[ -e /tmp/${SESSION} ] && rm -R /tmp/${SESSION}
